### ISSUE TITLE
Errors thrown in interceptors are consumed by the Bridge

### ISSUE THREAD

**Issue by Prinsn** [Breeze/breeze.bridge2.angular#12]
I'm not sure which side of things this is (currently fighting with karma and karma plugins that claim to provide better stack trace info) but I'm currently getting unit test failures of the pattern

```Uncaught Error: Uncaught (in promise): Error: undefined: undefined
Error: undefined: undefined
    at createError (http://localhost:9876/_karma_webpack_/webpack:/node_modules/breeze-client/breeze.debug.js:16247:1)
    at handleHttpError (http://localhost:9876/_karma_webpack_/webpack:/node_modules/breeze-client/breeze.debug.js:16237:1)
    at Object.error (http://localhost:9876/_karma_webpack_/webpack:/node_modules/breeze-client/breeze.debug.js:16074:1)
    at SafeSubscriber.errorFn [as _error] (http://localhost:9876/_karma_webpack_/webpack:/node_modules/breeze-bridge2-angular/index.js:172:1)
    at SafeSubscriber.push../node_modules/rxjs/_esm5/internal/Subscriber.js.SafeSubscriber.__tryOrUnsub (http://localhost:9876/_karma_webpack_/webpack:/node_modules/rxjs/_esm5/internal/Subscriber.js:192:1)
    at SafeSubscriber.push../node_modules/rxjs/_esm5/internal/Subscriber.js.SafeSubscriber.error (http://localhost:9876/_karma_webpack_/webpack:/node_modules/rxjs/_esm5/internal/Subscriber.js:143:1)
    at Subscriber.push../node_modules/rxjs/_esm5/internal/Subscriber.js.Subscriber._error (http://localhost:9876/_karma_webpack_/webpack:/node_modules/rxjs/_esm5/internal/Subscriber.js:79:1)
    at Subscriber.push../node_modules/rxjs/_esm5/internal/Subscriber.js.Subscriber.error (http://localhost:9876/_karma_webpack_/webpack:/node_modules/rxjs/_esm5/internal/Subscriber.js:59:1)
    at MapSubscriber.push../node_modules/rxjs/_esm5/internal/Subscriber.js.Subscriber._error (http://localhost:9876/_karma_webpack_/webpack:/node_modules/rxjs/_esm5/internal/Subscriber.js:79:1)
    at MapSubscriber.push../node_modules/rxjs/_esm5/internal/Subscriber.js.Subscriber.error (http://localhost:9876/_karma_webpack_/webpack:/node_modules/rxjs/_esm5/internal/Subscriber.js:59:1) thrown
```
Was conflicted about which breeze project this went with, but the highest reference to breeze in this case is the bridge itself, and I'm still trying to figure out what's going on.

reference in question

```
  at SafeSubscriber.errorFn [as _error] (http://localhost:9876/_karma_webpack_/webpack:/node_modules/breeze-bridge2-angular/index.js:172:1)
```

I don't know if this is a problem with internal error logging, but I'm currently stumped as to figure out what is actually failing, as `LOG: 'breeze error', Error: undefined: undefined` is pretty opaque

**Comment by Prinsn** [comment]
Actually, think I just figured out what it was doing.

I'm using an interceptor to mock the backend and was using a throw to notify the test that there was an unmapped endpoint in the interceptor, so that the test would fail with the information in question.

in errorFn() the `httpResponse` object is
```
{config: HttpRequest, data: "undefined: undefined", getHeaders: ƒ, status: undefined, ngConfig: HttpRequest, …}
config: HttpRequest {url: "http://localhost:9876/breeze/getTaxableIncomeForPeriod?periodId=0", body: null, reportProgress: false, withCredentials: false, responseType: "text", …}
data: "undefined: undefined"
getHeaders: ƒ getHeaders(headerName)
ngConfig: HttpRequest {url: "http://localhost:9876/breeze/getTaxableIncomeForPeriod?periodId=0", body: null, reportProgress: false, withCredentials: false, responseType: "text", …}
response: "http://localhost:9876/breeze/getTaxableIncomeForPeriod?periodId=0 is not mapped in the interceptor"
status: undefined
statusText: undefined
__proto__: Object
```

The response being the thrown error, and the "data" being what's returned to the unit test runner.

This both obfuscates the error, and will sometimes allow the test to pass (haven't quite figured out why on part 2).

This could very well be the intended and expected use case of HttpInterceptors, as I'm pretty green to Angular2.

**Comment by Prinsn** [comment]
The mock is working, so it's apparently not that hard to fix once you dig down far enough.

For anyone that has ended up here:

```        
var url = req.url.toLowerCase();
if (unmappedEndpoints.find(e => url.includes(e.toLowerCase())))
        {
            //As these are queryables, an empty array is a valid response
            return of(new HttpResponse({ body: "[]", status: 200 }));
        }
```

and just populate an array of all the endpoints you've yet to handle for

```        
var unmappedEndpoints = [ 
           ...
            "breeze/getpartnerbyid"
           ...
        ];
```

All normal defensive coding practices around handling breeze responses was sufficient and nothing other than the above had to be done.
